"""empty message

Revision ID: 38a229dce2b2
Revises: 6e0ca4b57fb9
Create Date: 2020-08-13 22:09:40.363384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38a229dce2b2'
down_revision = '6e0ca4b57fb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog', sa.Column('repaired', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalog', 'repaired')
    # ### end Alembic commands ###
